### ISSUE TITLE
Add support for MIPS devices

### ISSUE THREAD

**Issue by lars18th** [ferama/rospo#59]
Hi,

I tested to compile rospo for OpenWRT devices, and it works!
So I suggest to add these targets inside the `build.sh` script:
```
### multi arch binary build
GOOS=linux GOMIPS=softfloat GOARCH=mips build
GOOS=linux GOMIPS=softfloat GOARCH=mipsle build
```

Regards.

**Comment by lars18th** [comment]
Hi @ferama ,

You can merge the PR #60 to support it.

**Comment by ferama** [comment]
Merged. Thanks

**Comment by lars18th** [comment]
> Merged. Thanks

Don't mention it. However, I feel you'll need to update the README.md when you release the new builds. 😉
