### ISSUE TITLE
Question: webui ?

### ISSUE THREAD

**Issue by lars18th** [ferama/rospo#61]
Hi @ferama ,

From this code:
https://github.com/ferama/rospo/blob/af1bc6f3472353710a64cada56748fd4c9729c6f/pkg/web/web.go#L13-L14

I assume that a simple `http://127.0.0.1:8090/` will get a "nice UI". However, any GET to "/" responses with a 404 Error. I can only obtain responses using the API with `/api/tuns`, `/api/stats` and `/api/info`. Please could you document the webui more?

Thank you.

**Comment by ferama** [comment]
The UI was dropped in version 0.11
The comment you are referring needs to be cleaned up. 

The apis, although not documented, will still be able to create tunnels at runtime. Is a feature that I’m still evaluating If I want to maintain or not in future versions.

Actually, tunnels created through the apis are ephemeral and will be lost on rospo restart. 

The original use case was to create temporary tunnels at runtime but I didn’t received any feedback until now 🙂 Personally I don’t use them anymore so I preferred to focus on the kinds of things that I use every day

**Comment by lars18th** [comment]
Ok. So I suggest to remove any dead code. And I request if you can implement some "optional module compiling" to make binaries smaller.

**Comment by ferama** [comment]
I removed the unused web api in 0.11.5. The binary size decreased by a couple of MB

Thanks
